AWSTemplateFormatVersion: 2010-09-09
Parameters:
  infraStackName:
    Description: 'Name of your Infra CFN Stack'
    Type: String
Resources:
  # Route Table for Public Subnets
  routeTableForPublicSubnets:
    Type: AWS::EC2::RouteTable
    Properties: 
      Tags: 
        - Key: 'Name'
          Value: 'route-table-publicSubnets'
      VpcId:
        Fn::ImportValue:
          !Sub ${infraStackName}-VPC1ID 
  # Associate publicSubnet1 to RouteTable
  publicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Fn::ImportValue:
          !Sub ${infraStackName}-publicsubnet1ID
      RouteTableId:
        !Ref routeTableForPublicSubnets
  # Associate publicSubnet1 to RouteTable
  publicSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Fn::ImportValue:
          !Sub ${infraStackName}-publicsubnet2ID
      RouteTableId:
        !Ref routeTableForPublicSubnets
  # Associate publicSubnet1 to RouteTable
  publicSubnet3RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Fn::ImportValue:
          !Sub ${infraStackName}-publicsubnet3ID
      RouteTableId:
        !Ref routeTableForPublicSubnets
  heinMasterIGW:
    Type: AWS::EC2::InternetGateway
    Properties: 
      Tags: 
        - Key: 'Name'
          Value: 'hein master igw'
  attachVPCAndIGW:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties: 
      InternetGatewayId:
        !Ref heinMasterIGW
      VpcId:
        Fn::ImportValue:
          !Sub ${infraStackName}-VPC1ID 
  defaultRouteToIGW:
    Type: AWS::EC2::Route
    Properties: 
      DestinationCidrBlock: '0.0.0.0/0'
      GatewayId:
        !Ref heinMasterIGW
      RouteTableId:
        !Ref routeTableForPublicSubnets