AWSTemplateFormatVersion: 2010-09-09
Parameters:
  infraStackName:
    Description: 'Name of your Infra CFN Stack'
    Type: String
Resources: 
  customSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: 'open ssh, https, http'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: '0.0.0.0/0'
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: '0.0.0.0/0'
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: '0.0.0.0/0'
      VpcId:
        Fn::ImportValue:
          !Sub ${infraStackName}-VPC1ID
      Tags:
        - Key: 'Name'
          Value: 'SG-VPC-Security Group'