AWSTemplateFormatVersion: 2010-09-09
Parameters:
  infraStackName:
    Description: 'Name of your Infra CFN Stack'
    Type: String
    Default: infra-stack-v3
Resources:
  privateSubnet1:
    Type: AWS::EC2::Subnet
    Properties: 
      AvailabilityZone: 'ap-southeast-1a'
      CidrBlock: '192.168.4.0/24'
      MapPublicIpOnLaunch: false
      Tags: 
        - Key: 'Name'
          Value: 'private-subnet1'
      VpcId:
        Fn::ImportValue:
          !Sub ${infraStackName}-VPC1ID
  privateSubnet2:
    Type: AWS::EC2::Subnet
    Properties: 
      AvailabilityZone: 'ap-southeast-1b'
      CidrBlock: '192.168.5.0/24'
      MapPublicIpOnLaunch: false
      Tags: 
        - Key: 'Name'
          Value: 'private-subnet2'
      VpcId:
        Fn::ImportValue:
          !Sub ${infraStackName}-VPC1ID
  privateSubnet3:
    Type: AWS::EC2::Subnet
    Properties: 
      AvailabilityZone: 'ap-southeast-1c'
      CidrBlock: '192.168.6.0/24'
      MapPublicIpOnLaunch: false
      Tags: 
        - Key: 'Name'
          Value: 'private-subnet3'
      VpcId:
        Fn::ImportValue:
          !Sub ${infraStackName}-VPC1ID
Outputs:
  privateSubnet1ID:
    Description: "private subnet-1 ID"
    Value:
      !Ref privateSubnet1
    Export:
      Name:
        !Sub ${AWS::StackName}-privateSubnet1ID
  privateSubnet2ID:
    Description: "private subnet-2 ID"
    Value:
      !Ref privateSubnet2
    Export:
      Name:
        !Sub ${AWS::StackName}-privateSubnet2ID
  privateSubnet3ID:
    Description: "private subnet-3 ID"
    Value:
      !Ref privateSubnet3
    Export:
      Name:
        !Sub ${AWS::StackName}-privateSubnet3ID