# In this stack, Step-1 - 3 public subnets associate to public Route Table!!!!
################ Step-2 - Create Internet Gateway and attach to VPC !!!
################ Step-3 - Defaute Route to Internet Gateway(IGW) in Public Route Table!!!!
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  infraStackName:
    Description: "This is infra Stack Name"
    Type: String
    Default: infra-stack-v3 
Resources:
  publicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      RouteTableId:
        Fn::ImportValue:
          !Sub ${infraStackName}-PublicRouteTBID      
      SubnetId:
        Fn::ImportValue:
          !Sub ${infraStackName}-PublicSubnet1ID
  publicSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      RouteTableId:
        Fn::ImportValue:
          !Sub ${infraStackName}-PublicRouteTBID      
      SubnetId:
        Fn::ImportValue:
          !Sub ${infraStackName}-PublicSubnet2ID
  publicSubnet3RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      RouteTableId:
        Fn::ImportValue:
          !Sub ${infraStackName}-PublicRouteTBID      
      SubnetId:
        Fn::ImportValue:
          !Sub ${infraStackName}-PublicSubnet3ID
  IGW:
    Type: AWS::EC2::InternetGateway
    Properties: 
      Tags: 
        - Key: Name
          Value: SGVPC1IGW 
#In this Step, If you check in AWS Console under Internet Gateway,
#will just create IGW, but it show in status "Detached". So, Let's attach to SGVPC1 !!!!
  igwAttachToSGVPC:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties: 
      InternetGatewayId: 
        !Ref IGW
      VpcId:
        Fn::ImportValue:
          !Sub ${infraStackName}-VPC1ID
#Write Default Route in public Route Table gateway to IGW!!!!!!
  defaultRouteToIGW:
    Type: AWS::EC2::Route
    Properties: 
      DestinationCidrBlock: '0.0.0.0/0'
      GatewayId:
        !Ref IGW
      RouteTableId:
        Fn::ImportValue:
          !Sub ${infraStackName}-PublicRouteTBID 


    
